### ISSUE TITLE
Migration to the news API of SQLAlchemy

### ISSUE THREAD

**Issue by jssuzanne** [AnyBlok/AnyBlok#168]
The goal is to migrate to the SQLAlchemy 2 API

The major problems encountered are:
- SQLA adds a class attribute named 'registry', which conflicts with AnyBlok's registry: [SQLA registry](https://docs.sqlalchemy.org/en/14/orm/mapping_api.html#sqlalchemy.orm.registry)
- A new API to query the database (select, update, delete) more homogeneous and closer to the representation of SQL appears in version 1.4 and will be the main API in version 2.0. It is very likely that the old API will be deprecated and deleted in the long run. [New API](https://docs.sqlalchemy.org/en/14/changelog/migration_20.html#migration-orm-usage)
- A new connection API [Future Engine](https://docs.sqlalchemy.org/en/14/changelog/migration_20.html#migration-to-2-0-step-four-use-the-future-flag-on-engine), [Future Session](https://docs.sqlalchemy.org/en/14/changelog/migration_20.html#migration-to-2-0-step-four-use-the-future-flag-on-session)

There are two main areas to deal with:
- rename the registry from AnyBlok to anyblok, without breaking the short / medium term compatibility.
- Add the new API as soon as possible while maintaining the old one as long as possible

For this we will provide 3 branches associated with a millestones
- master / main (1.1.0):
  - [x] SQLA version <1.4 #173 
  - [x] Add anyblok attribute instead of registry (#172, #177)
  - [x] the registry becomes a property which points to the attribute anyblok + deprecation message. (#172, #177)
  - [x] Update documentation 
- sqla_1_4 (1.2.0)
  - [x] version of SQLA <= 1.4 SQLA <2.0. (#166, #178) 
  - [x] Overload the SQLA registry to dispatch between the two registrys + deprecation message #166 
  - [x] Set up helpers for the new SQLA API. (#175, #178)
  - [x] Add deprecation messages on the old API helppers (Query.update, Query.delete) #175 
  - [x] Switch to the new connection API. #181 
  - [x] Modify as much as possible the calling codes of the deprecated code (#166, #175, #181)
  - [x] Increase test coverage (#184)
  - [x] Remove deprecation warnings from other library (#166, #178, #179, #180)
  - [x] Verify that SQLA_Utils and SQLA_views are migrated (https://github.com/kvesteri/sqlalchemy-utils/pull/506, https://github.com/jklukas/sqlalchemy-views/pull/17)

- sqla_2 (2.0.0)
  - [X] remove of properties named registy and replace them by anyblok
  - [X] SQL> = 2.0
  - [X] new Query API #176 
  - [X] clean up APIs removed from SQLA
  - [X] clean all deprecated behaviours
  - [X] Modify as much as possible the calling codes of the deprecated code (#176,)
  - [x] update sqlalchemy-views https://github.com/jklukas/sqlalchemy-views/pull/25

**Comment by jssuzanne** [comment]
Thank for all the member of the code print of the PyConFR 2023 at Bordeaux
