### ISSUE TITLE
Deprecate plugins group in the configuration

### ISSUE THREAD

**Issue by jssuzanne** [AnyBlok/AnyBlok#189]
The goal is to removed theses plugins in version 2

```
Plugins:
  --registry-cls REGISTRY
                        Registry class to use
  --migration-cls MIGRATION
                        Migration class to use
  --get-url-fnct GET_URL
                        get_url function to use
```

these functions is too specific to be overwritted.

- [X] Add the deprecation behaviour in the configuration definition and helper **add_argument** #190 
- [x] Add the remove behaviour in the configuration definition and helper **add_argument** #191
- [X] Add the deprecated message on **Configuration.set** #190
- [x] Add the exception on removed on **Configuration.set** #191 
- [X] Add the deprecated message on **Configuration.get** #190 
- [x] Add the exception on removed on **Configuration.get** #191
- [x] Add removed on the configuration on branch 2.0 #192
- [x]  Remove the configuration on branch 2.1 #194
